# Generated by Django 6.1 on 2026-08-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المجال')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'مجال',
                'verbose_name_plural': 'المجالات',
            },
        ),
    ]
