# Generated by Django 6.1 on 2026-08-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المسار')),
                ('description', models.TextField(blank=True, verbose_name='وصف عام للمسار')),
            ],
            options={
                'verbose_name': 'مسار',
                'verbose_name_plural': 'المسارات',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'محور', 'verbose_name_plural': 'المحاور'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='اسم المحور'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.category', verbose_name='المحور'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tracks',
            field=models.ManyToManyField(related_name='domains', to='core.track', verbose_name='المسارات'),
        ),
    ]
