# Generated by Django 6.1 on 2026-08-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_track_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان الهدف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('due_datetime', models.DateTimeField(verbose_name='الموعد الزمني للتنفيذ')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل'), ('DELAYED', 'متأخر'), ('EXTENDED', 'ممدد')], default='PENDING', max_length=20, verbose_name='حالة التنفيذ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات المشرف/الطالب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.domain', verbose_name='المجال')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.track', verbose_name='المسار')),
            ],
            options={
                'verbose_name': 'هدف',
                'verbose_name_plural': 'الأهداف',
                'ordering': ['due_datetime'],
            },
        ),
    ]
