# Generated by Django 6.1 on 2026-08-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت الإنجاز الفعلي'),
        ),
    ]
