# Generated by Django 6.1 on 2026-08-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_goal_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المرسل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=255, verbose_name='عنوان الموضوع')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('read', 'تمت قراءتها'), ('replied', 'تم الرد')], default='new', max_length=10, verbose_name='حالة الرسالة')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل'), ('DELAYED', 'متأخر'), ('EXTENDED', 'ممدد')], default='IN_PROGRESS', max_length=20, verbose_name='حالة التنفيذ'),
        ),
    ]
